### PR TITLE
implement Runtime::resize_memory()

### LINKED ISSUE #13: expose a wasm3 runtime's `memoryLimit`
wasm3 allows one to limit the amount of memory available to the runtime through the following code:

https://github.com/wasm3/wasm3/blob/640bf0cc2671f1725234536c3cd4be50de6cc19e/source/m3_env.h#L246

Which can be modified either by changing `memoryLimit` directly or by calling `ResizeMemory`, which takes an `IM3Runtime` as well as the number of pages:

https://github.com/wasm3/wasm3/blob/bdc50827555399c51316273ef15b3358ca196e41/source/m3_env.c#L454

The ability to limit the maximum number of pages available to the runtime is important in environments where the device running wasm3 can only allocate a few pages of memory.

Would you accept a PR to allow resizing the runtime's allocated memory?

### PR DESCRIPTION
**Pull request by bacongobbler**
This function will resize the number of allocated pages to `num_pages`. A unit test has been provided to demonstrate how to resize the runtime.

closes #13

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by Veykril** [comment]
The reason as to why you aren't seeing the error string in the panic is that I only implemented Display to dereference the CString. A panic on the other hand only shows a values debug formatting, the error message you are getting is "runtime ran out of memory".

**Comment by Veykril** [comment]
And it seems the reason as to why this errors is that if no modules are loaded the maxPages var is set to 0, so reallocating at that point will always error as this limit is only set once modules are loaded.

**Comment by bacongobbler** [comment]
> I just pushed a fix so it displays properly.

I don't see the fix in master. Where would your fix be?

Thank you for helping me with this!

It's interesting that maxPages would be set to 0 without any modules loaded, especially since `Runtime::new()` asks for the requested number of pages. You'd think the runtime could be set up before loading a module into the runtime. In either case, thank you for finding that. I'll fiddle around with the test and load a bogus module into the runtime then resize the page size.

**Comment by Veykril** [comment]
> I don't see the fix in master. Where would your fix be?

Turns out I tried pushing without rebasing first so it failed but I didn't notice that. 40d7a02aa1b578fbbfc4e134f5dac30ccdc34217 manually implements `Debug` now.

> It's interesting that maxPages would be set to 0 without any modules loaded, especially since Runtime::new() asks for the requested number of pages.

That's actually not quite right, the number you supply to the runtime is the stack size in bytes, not the number of memory pages.

**Comment by bacongobbler** [comment]
All right that oughta do it! Let me know if you'd like me to add further tests elsewhere.

**Pull request merged**
