### PR TITLE
fix: Calculates the offset by sizeof

### PR DESCRIPTION
**Pull request by douchuan**

### CODE REVIEW

**Comment by Veykril** [comment]
What exactly does this fix? [`ptr::add`](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) work in units of T, so this change offsets the pointer by `size_of::<u32/u64> * size_of::<ParamterType>` which is very much wrong to my knowledge.

**Comment by douchuan** [comment]
I declare the custom extension fn like this:

mod env {
    extern "C" {
        pub fn add_u32(a: u32, b: u32) -> u32;
        pub fn add_u8(a: u8, b: u8) -> u32;
    }
}

the value of  'b' is wrong. 'a' 's type is 'u32', should offset by 4.

**Comment by douchuan** [comment]
My mistake, just ignore it.

The exact bug is: **can't get the second arg's val** .

I declare extensions like this:

```
mod env {
    extern "C" {
        pub fn add_u32(a: u32, b: u32) -> u32;
    }
}

```

and, used it like this:

```
wasm3::make_func_wrapper!(add_u32_wrap: add_u32(a: u32, b: u32) -> u32);
fn add_u32(a: u32, b: u32) -> u32 {
    a + b
}

```
the 'b''s value isn't right.

I check wasm3 code, found:

m3_compile.c, CompileCallArgsAndReturn, say:

```

   u32 slotsPerArg = sizeof (u64) / sizeof (m3slot_t);
    // args are 64-bit aligned
    u16 argTop = topSlot + numArgs * slotsPerArg;

```

so,
**the value SIZE_IN_SLOT_COUNT of u32, should '2'**

**Comment by Veykril** [comment]
Ah yes, I also noticed this probably earlier today, https://github.com/Veykril/wasm3-rs/issues/12. Can you try with default features off and see if the problem persists?

```toml
[dependencies.wasm3]
git = "https://github.com/Veykril/wasm3-rs"
default-features = false
```

**Comment by douchuan** [comment]
it's ok with 'default-features = false'

**Comment by Veykril** [comment]
#56858c8 should've fixed this, please let me know if it did for you.

**Comment by douchuan** [comment]
Thanks, it worked for me, great work.

**Comment by Veykril** [comment]
Aight, thanks for confirming 😄

**Pull request closed without merging**
